name: Deploy go backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # this tells git to use temporary ubuntu vm/container
    runs-on: ubuntu-latest

    steps:
      - name: setup VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          # This basically tells that if there is no db name called ai tutor, then (using | meaning forward the value)
          # grep means take the previous value and compare if the value is equal to 1
          # if it's true then it won't execute next command (remember || means or)
          
          # /dev/null is linux blackhole, meaning you can throw anything to it
          # &> means redirect the output to x
          # 
          script: |
            if ! command -v psql &> /dev/null 
            then 
              sudo apt update
              sudo apt install -y postgresql postgresql-contrib
            fi
            sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'default'"
            sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname = 'ai_tutor'" | grep -q 1 || \
            sudo -u postgres createdb ai_tutor 
          
      # download repository code into github action runner (this is like a github clone)
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create config file 
        run: |

          cat <<EOF > ./files/config.yaml
          ${{ secrets.APP_CONFIG }}
          EOF

          cat <<EOF > ./files/google-account-service.json
          ${{ secrets.GOOGLE_SERVICE }}
          EOF

          cat <<EOF > ./files/keys/private.pem 
          ${{ secrets.PRIVATE_KEY }}
          EOF
      
      # install Go 1.23 on temporary runner
      - name: Setup go 
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binary
      # Build binary for linux executables
      # with amd64 architecture
      # the binary is named with 'app'
        run: |
          go mod tidy
          GOOS=linux GOARCH=amd64 go build -o app ./cmd
      - name: Copy binary to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          source: "app,files,migrations"
          target: /opt/aiconvbe
      - name: Restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            chmod +x /opt/aiconvbe/app 
            sudo systemctl restart ai-conv-be 